#### 1. 定义两个不同的图

In [1]:
import tensorflow as tf

g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v", [1], initializer = tf.zeros_initializer()) # 设置初始值为0

g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable("v", [1], initializer = tf.ones_initializer())  # 设置初始值为1
    
with tf.Session(graph = g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

with tf.Session(graph = g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

[ 0.]
[ 1.]


#### 2. 张量的概念

In [2]:
import tensorflow as tf
a = tf.constant([1.0, 2.0], name="a")
b = tf.constant([2.0, 3.0], name="b")
result = a + b
print result

sess = tf.InteractiveSession ()
print(result.eval())
sess.close()

Tensor("add:0", shape=(2,), dtype=float32)
[ 3.  5.]


#### 3. 会话的使用

3.1 创建和关闭会话

In [3]:
# 创建一个会话。
sess = tf.Session()

# 使用会话得到之前计算的结果。
print(sess.run(result))

# 关闭会话使得本次运行中使用到的资源可以被释放。
sess.close()

[ 3.  5.]


3.2 使用with statement 来创建会话

In [4]:
with tf.Session() as sess:
    print(sess.run(result))

[ 3.  5.]


3.3 指定默认会话

In [5]:
sess = tf.Session()
with sess.as_default():
     print(result.eval())

[ 3.  5.]


In [6]:
sess = tf.Session()

# 下面的两个命令有相同的功能。
print(sess.run(result))
print(result.eval(session=sess))

[ 3.  5.]
[ 3.  5.]


#### 4. 使用tf.InteractiveSession构建会话

In [7]:
sess = tf.InteractiveSession ()
print(result.eval())
sess.close()

[ 3.  5.]


#### 5. 通过ConfigProto配置会话

In [1]:
config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)
sess1 = tf.InteractiveSession(config=config)
sess2 = tf.Session(config=config)

NameError: name 'tf' is not defined

# 变量
## 创建
weights = tf.Variable(tf.random_normal([784, 200], stddev=0.35),    
                      name="weights")    
biases = tf.Variable(tf.zeros([200]), name="biases")    

filter_weight = tf.get_variable('weights', [2, 2, 1, 1], initializer = tf.constant_initializer([
                                                                        [1, -1],
                                                                        [0, 2]]))    
tf.get_variable跟tf.Variable都可以用来定义图变量，但是前者的必需参数（即第一个参数）并不是图变量的初始值，而是图变量的名称。    
tf.Variable的用法要更丰富一点，当指定名称的图变量已经存在时表示获取它，当指定名称的图变量不存在时表示定义它    

## 生成tensor    
tf.zeros(shape, dtype=tf.float32, name=None)    
tf.zeros_like(tensor, dtype=None, name=None)    
tf.constant(value, dtype=None, shape=None, name='Const')    
tf.fill(dims, value, name=None)    
tf.ones_like(tensor, dtype=None, name=None)      
tf.ones(shape, dtype=tf.float32, name=None)    

## 生成序列
tf.range(start, limit, delta=1, name='range')    
tf.linspace(start, stop, num, name=None)    

## 生成随机数
tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)    
tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)    
tf.random_uniform(shape, minval=0.0, maxval=1.0, dtype=tf.float32, seed=None, name=None)    
tf.random_shuffle(value, seed=None, name=None)    

## 赋值
tf.assign(state,new_value)    

##初始化
tf.initialize_all_variables()    

In [5]:
import tensorflow as tf
#Two Variable Initializer

filter_weight = tf.Variable(tf.constant([[[[1]], [[-1]]],[[[0]],[[2]]]]),shape=[2,2,1,1])

"""
filter_weight = tf.get_variable('weights', [2, 2, 1, 1], initializer = tf.constant_initializer([
                                                                        [1, -1],
                                                                        [0, 2]]))

注意这里的constant_initializer的shape,实际结果如下：
[[
  [[ 1.]] 
  [[-1.]]
 ],
 [
  [[ 0.]]
  [[ 2.]]
 ]
]
"""
print("filter_weight:",filter_weight)

filter_weight: <tf.Variable 'Variable:0' shape=(2, 2, 1, 1) dtype=int32_ref>


In [4]:
import tensorflow as tf
import numpy as np

M = np.array([
        [[1],[-1],[0]],
        [[-1],[2],[1]],
        [[0],[2],[-2]]
    ])

print ("Matrix shape is: ",M.shape)
M = np.asarray(M, dtype='float32')
M = M.reshape(1, 3, 3, 1)
print("M:",M)
"""
[[
   [
    [ 1.]
    [-1.]
    [ 0.]
   ],
   [[-1.]
     [ 2.]
     [ 1.]
   ],
   [
    [ 0.]
    [ 2.]
    [-2.]
   ]
 ]]
"""

Matrix shape is:  (3, 3, 1)
M: [[[[ 1.]
   [-1.]
   [ 0.]]

  [[-1.]
   [ 2.]
   [ 1.]]

  [[ 0.]
   [ 2.]
   [-2.]]]]


'\n[[\n   [\n    [ 1.]\n    [-1.]\n    [ 0.]\n   ],\n   [[-1.]\n     [ 2.]\n     [ 1.]\n   ],\n   [\n    [ 0.]\n    [ 2.]\n    [-2.]\n   ]\n ]]\n'

## TF.VARIABLE、TF.GET_VARIABLE、TF.VARIABLE_SCOPE以及TF.NAME_SCOPE关系
1. tf.Variable与tf.get_variable
    tensorflow提供了通过变量名称来创建或者获取一个变量的机制。通过这个机制，在不同的函数中可以直接通过变量的名字来使用变量，而不需要将变量通过参数的形式到处传递。TensorFlow中通过变量名获取变量的机制主要是通过 **tf.get_variable和tf.variable_scope** 实现的。        当然，变量也可以通过tf.Varivale来创建。当tf.get_variable用于变量创建时，和tf.Variable的功能基本等价。    
```
#以下两个定义是等价的
v = tf.get_variable('v', shape=[1], initializer=tf.constant_initializer(1.0))
v = tf.Variable(tf.constant(1.0, shape=[1], name='v')
```
    tf.get_varialbe和tf.Variable最大的区别在于：tf.Variable的变量名是一个可选项，通过name=’v’的形式给出。但是tf.get_variable必须指定变量名。    
1. 使用tf.Variable时，如果检测到命名冲突，系统会自己处理。使用tf.get_variable()时，系统不会处理冲突，而会报错
```
import tensorflow as tf
w_1 = tf.Variable(3,name="w_1")
w_2 = tf.Variable(1,name="w_1")
print w_1.name
print w_2.name
#输出
#w_1:0
#w_1_1:0
```

1. tf.get_variable与tf.variable_scope    
    上面已经提到过了：TensorFlow中通过变量名获取变量的机制主要是通过tf.get_variable和tf.variable_scope实现的。在这里，我主要解释下大家深恶痛绝的reuse问题。    
    其实只要记住一件事情就ok了：当reuse为False或者None时（这也是默认值），同一个tf.variable_scope下面的变量名不能相同；当reuse为True时，tf.variable_scope只能获取已经创建过的变量。    
    下面我们通过代码来看下：    
    
```    
#reuse=False时会报错的情况：    
with tf.variable_scope('foo'):
    v = tf.get_variable('v',[1],initializer=tf.constant_initializer(1.0))
 
with tf.variable_scope('foo'):
    v1 = tf.get_variable('v',[1])
        
```        
    在这种情况下会报错：Variable foo/v already exists, disallowed.Did you mean to set reuse=True in Varscope?    
    其原因就是在命名空间foo中创建了相同的变量。如果我要在foo下创建一个变量v1，其name=‘v’，只需要将reuse设置为Ture就ok了。将上面第二部分代码修改为：    
```        

with tf.variable_scope('foo', reuse=True):
    v1 = tf.get_variable('v',[1])
    print(v1.name)      #结果为foo/v
```    
    当reuse已经设置为True时，tf.variable_scope只能获取已经创建过的变量。这个时候，在命名空间bar中创建name=‘v’的变量v3，将会报错错：Variable bar/v dose not exists, diallowed. Did you mean to set reuse=None in VarScope?  
    
```    
with tf.variable_scope('bar', reuse=True):
    v3 = tf.get_variable('v',[1])
```    
    简而言之，reuse=False时，tf.variable_scope创建变量；reuse=True时，tf.variable_scope获取变量。    
1. tf.variable_scope与tf.name_scope    
    除了tf.variable_scope，tf.name_scope函数也提供了命名空间管理的功能。这两个函数在大部分情况下是等价的，唯一的区别是在使用    tf.get_variable函数时。    
    tf.get_variable函数不受tf.name_scope的影响。    
    我们从代码看下这句话的具体意思。    
    首先是tf.variable_scope：    
```    
with tf.variable_scope('foo'):
    a = tf.get_variable('bar',[1])
    print(a.name)#结果为foo/bar:0  
``` 
再看tf.name_scope：        
    ```
with tf.name_scope('a'):
    a=tf.Variable([1])
    print(a.name)#结果为a/Variable:0
 
    b=tf.get_variable('b',[1])
    print(b.name)#结果为b:0   
 
    ```            

    从这个结果中，我们能很清晰地看到，tf.get_variable创建的变量并不是a/b:0，而是b:0。这就表示了在tf.name_scope函数下，    tf.get_variable不受其约束。    