In [1]:
import numpy as np

#### 1.  定义RNN的参数。

In [37]:
X = [[1,1],[1,1],[1,1],[1,1]]
state = [0.0, 0.0]
w_cell_state = np.asarray([[0.1, 0.2], [0.3, 0.4]])
w_cell_input = np.asarray([0.5, 0.6])
b_cell = np.asarray([0.1, -0.1])
w_output = np.asarray([[1.0], [2.0]])
b_output = 0.1

#### 2.  执行前向传播过程。

In [38]:
print("state:",state)
print("    ")
for i in range(len(X)):
    print("dot:",i, state, "\n",w_cell_state,"\n", np.dot(state, w_cell_state),"\n", X[i] * w_cell_input)
    before_activation = np.dot(state, w_cell_state) + X[i] * w_cell_input + b_cell
    state = np.tanh(before_activation)
    final_output = np.dot(state, w_output) + b_output
    print ("before activation: ", before_activation)
    print ("state: ", state)
    print ("output: ", final_output)
    print("rnn:",i,X[i], state, final_output)
    print("    ")

state: [0.0, 0.0]
    
dot: 0 [0.0, 0.0] 
 [[0.1 0.2]
 [0.3 0.4]] 
 [0. 0.] 
 [0.5 0.6]
before activation:  [0.6 0.5]
state:  [0.53704957 0.46211716]
output:  [1.56128388]
rnn: 0 [1, 1] [0.53704957 0.46211716] [1.56128388]
    
dot: 1 [0.53704957 0.46211716] 
 [[0.1 0.2]
 [0.3 0.4]] 
 [0.1923401  0.29225678] 
 [0.5 0.6]
before activation:  [0.7923401  0.79225678]
state:  [0.65973266 0.6596856 ]
output:  [2.07910385]
rnn: 1 [1, 1] [0.65973266 0.6596856 ] [2.07910385]
    
dot: 2 [0.65973266 0.6596856 ] 
 [[0.1 0.2]
 [0.3 0.4]] 
 [0.26387894 0.39582077] 
 [0.5 0.6]
before activation:  [0.86387894 0.89582077]
state:  [0.69825081 0.71425683]
output:  [2.22676447]
rnn: 2 [1, 1] [0.69825081 0.71425683] [2.22676447]
    
dot: 3 [0.69825081 0.71425683] 
 [[0.1 0.2]
 [0.3 0.4]] 
 [0.28410213 0.42535289] 
 [0.5 0.6]
before activation:  [0.88410213 0.92535289]
state:  [0.70846842 0.7284199 ]
output:  [2.26530822]
rnn: 3 [1, 1] [0.70846842 0.7284199 ] [2.26530822]
    
